version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    ports:
      - "3000:80"
  
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdbname
    depends_on:
      - mongo
#22IT118
  mongo:
    image: mongo
    ports:
      - "27017:27017"
